/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    'service-details': ServiceDetail;
    guides: Guide;
    'service-areas': ServiceArea;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'service-details': ServiceDetailsSelect<false> | ServiceDetailsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Contenu des trois pages principales du site. Pour créer une page, utilisez « Prestations ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Repère interne, non affiché sur le site. Ex : « Accueil ».
   */
  title: string;
  /**
   * Fixé par le code : cette page est adossée à une route précise.
   */
  slug: string;
  hero: {
    eyebrow?: string | null;
    /**
     * Première partie du titre, en blanc.
     */
    title: string;
    /**
     * Suite du titre, affichée en doré.
     */
    highlight?: string | null;
    text: string;
    image: number | Media;
    /**
     * Deux boutons au maximum. Le premier est mis en avant. Le lien est automatique : « Appeler » utilise le téléphone de la configuration du site, « Formulaire » renvoie vers la page contact.
     */
    ctas?:
      | {
          /**
           * Ex : « Appelez-moi maintenant ».
           */
          label: string;
          target: 'phone' | 'contact';
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Laisser le titre vide pour ne pas afficher la section.
   */
  intro?: {
    title?: string | null;
    body?: string | null;
  };
  /**
   * Sections alternées image/texte.
   */
  features?:
    | {
        title: string;
        body: string;
        image: number | Media;
        imageSide?: ('left' | 'right') | null;
        /**
         * Laisser vide pour ne pas afficher de bouton.
         */
        ctaLabel?: string | null;
        /**
         * Ex : /depannage-electrique
         */
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  servicesTitle?: string | null;
  servicesIntro?: string | null;
  services?:
    | {
        title: string;
        description: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  seo: {
    /**
     * Idéalement 50-60 caractères.
     */
    title: string;
    /**
     * Idéalement 150-160 caractères.
     */
    description: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrit l'image pour les lecteurs d'écran et Google. Ex : « Tableau électrique remis aux normes à Saintes ».
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Pages détaillées listées sous « Électricité générale ». En créer une ajoute sa page et son entrée de menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-details".
 */
export interface ServiceDetail {
  id: number;
  /**
   * Libellé court affiché dans le menu et le pied de page. Ex : « Tableau électrique ».
   */
  navLabel: string;
  /**
   * Adresse de la page : /mon-slug. Sans accent. À NE PLUS MODIFIER une fois la page indexée par Google.
   */
  slug: string;
  /**
   * Les plus petits nombres apparaissent en premier.
   */
  order: number;
  hero: {
    /**
     * Petite ligne au-dessus du titre. Ex : « Électricité générale · Saintes ».
     */
    eyebrow?: string | null;
    /**
     * Première partie du titre, en blanc. Ex : « Tableau ».
     */
    title: string;
    /**
     * Suite du titre, affichée en doré. Ex : « électrique ».
     */
    highlight?: string | null;
    text: string;
    image: number | Media;
  };
  intro: string;
  /**
   * Grille de cartes présentant ce que couvre l'intervention.
   */
  benefits: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  /**
   * Liste numérotée, facultative. Laissez vide pour ne pas afficher la section.
   */
  steps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Liens affichés en bas de page (maillage interne). Ne vous sélectionnez pas vous-même.
   */
  related?: (number | ServiceDetail)[] | null;
  seo: {
    /**
     * Idéalement 50-60 caractères.
     */
    title: string;
    /**
     * Idéalement 150-160 caractères.
     */
    description: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles de conseil publiés sur /guides. Un guide enregistré en brouillon n'apparaît pas sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * Partie finale de l'adresse : /guides/mon-slug. À NE PLUS MODIFIER une fois le guide indexé par Google.
   */
  slug: string;
  /**
   * Les plus petits nombres apparaissent en premier sur /guides.
   */
  order: number;
  category: 'Sécurité' | 'Budget' | 'Rénovation' | 'Dépannage';
  readingMinutes: number;
  /**
   * Affichée sur le guide et envoyée à Google (schema).
   */
  updated: string;
  /**
   * Résumé affiché dans la liste des guides et lors des partages.
   */
  excerpt: string;
  image: number | Media;
  body: (
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'p';
      }
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'h2';
      }
    | {
        items: {
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'ul';
      }
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'callout';
      }
  )[];
  /**
   * Alimente le maillage interne et les liens en bas de guide.
   */
  relatedServices?: (number | ServiceDetail)[] | null;
  /**
   * Affichées en bas du guide et envoyées à Google (FAQ schema).
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo: {
    /**
     * Idéalement 50-60 caractères. Peut différer du titre affiché.
     */
    title: string;
    /**
     * Idéalement 150-160 caractères.
     */
    description: string;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Communes où vous intervenez. Chacune obtient sa page /electricien/<slug> et apparaît dans le menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: number;
  /**
   * Tel qu'affiché sur le site. Ex : « Saint-Jean-d'Angély ».
   */
  name: string;
  /**
   * À cocher UNIQUEMENT pour Saintes (siège de l'entreprise). Cette commune n'a pas de page dédiée : c'est déjà l'accueil du site.
   */
  base?: boolean | null;
  /**
   * Partie finale de l'adresse : /electricien/mon-slug. Sans accent ni apostrophe (ex : saint-jean-d-angely). À NE PLUS MODIFIER une fois la page indexée par Google.
   */
  slug?: string | null;
  /**
   * Affichée sur la page de la commune. Inutile pour la commune de rattachement.
   */
  distanceKm?: number | null;
  /**
   * Phrase d'introduction de la page, en haut. IMPORTANT pour le référencement : écrivez un texte UNIQUE pour chaque commune — un texte recopié d'une ville à l'autre est pénalisé par Google.
   */
  intro?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'service-details';
        value: number | ServiceDetail;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: number | ServiceArea;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        text?: T;
        image?: T;
        ctas?:
          | T
          | {
              label?: T;
              target?: T;
              id?: T;
            };
      };
  intro?:
    | T
    | {
        title?: T;
        body?: T;
      };
  features?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        imageSide?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  servicesTitle?: T;
  servicesIntro?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-details_select".
 */
export interface ServiceDetailsSelect<T extends boolean = true> {
  navLabel?: T;
  slug?: T;
  order?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        text?: T;
        image?: T;
      };
  intro?: T;
  benefits?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  related?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  category?: T;
  readingMinutes?: T;
  updated?: T;
  excerpt?: T;
  image?: T;
  body?:
    | T
    | {
        p?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        h2?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        ul?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  relatedServices?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  name?: T;
  base?: T;
  slug?: T;
  distanceKm?: T;
  intro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Coordonnées, horaires, avis et questions fréquentes. Ces informations apparaissent sur TOUTES les pages du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  legalName: string;
  /**
   * 14 chiffres. Obligatoire dans les mentions légales. Saisissez-le avec ou sans espaces : la mise en forme est automatique.
   */
  siret?: string | null;
  /**
   * Utilisé dans le titre des pages. Ex : « Électricien à Saintes ».
   */
  slogan: string;
  /**
   * Meta description de l'accueil et partages sur les réseaux.
   */
  description: string;
  phone: {
    /**
     * Tel qu'il apparaît sur le site. Ex : 06 68 87 49 41.
     */
    display: string;
    /**
     * Utilisé par les boutons « Appeler ». Format +33… sans espace. Ex : +33668874941.
     */
    e164: string;
  };
  email?: string | null;
  address: {
    street: string;
    postalCode: string;
    city: string;
    country: string;
  };
  googleMapsUrl: string;
  /**
   * Fiche Google, réseaux sociaux… Envoyés à Google pour relier le site à l'entreprise.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Position de l'établissement, envoyée à Google (SEO local).
   */
  geo: {
    lat: number;
    lng: number;
  };
  /**
   * Texte libre, affiché tel quel sur le site.
   */
  hours: {
    /**
     * Ex : « Lundi – Vendredi ».
     */
    label: string;
    /**
     * Ex : « 8 h – 18 h » ou « Fermé ».
     */
    value: string;
    id?: string | null;
  }[];
  /**
   * Version machine des horaires, envoyée à Google. À garder cohérente avec les horaires affichés ci-dessus.
   */
  openingHoursSpec?:
    | {
        days: ('Mo' | 'Tu' | 'We' | 'Th' | 'Fr' | 'Sa' | 'Su')[];
        /**
         * Format 24 h. Ex : 08:00.
         */
        opens: string;
        /**
         * Format 24 h. Ex : 18:00.
         */
        closes: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Affiché sur le site (« dans un rayon d'environ X km ») et dans la FAQ.
   */
  serviceRadiusKm: number;
  /**
   * Bandeau affiché sous le hero des pages.
   */
  trustBadges?:
    | {
        icon: number | Media;
        label: string;
        /**
         * À cocher pour une icône noire, afin de la passer en blanc.
         */
        invert?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ⚠️ UNIQUEMENT de VRAIS avis clients — publier de faux avis est illégal en France. Recopiez vos avis Google à l'identique. La section « avis » et la note moyenne apparaissent dès qu'un avis est présent.
   */
  reviews?:
    | {
        author: string;
        rating: number;
        text: string;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Affichées sur l'accueil et les pages ville, et envoyées à Google (FAQ schema).
   */
  faq: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  siret?: T;
  slogan?: T;
  description?: T;
  phone?:
    | T
    | {
        display?: T;
        e164?: T;
      };
  email?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  googleMapsUrl?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  hours?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  openingHoursSpec?:
    | T
    | {
        days?: T;
        opens?: T;
        closes?: T;
        id?: T;
      };
  serviceRadiusKm?: T;
  trustBadges?:
    | T
    | {
        icon?: T;
        label?: T;
        invert?: T;
        id?: T;
      };
  reviews?:
    | T
    | {
        author?: T;
        rating?: T;
        text?: T;
        date?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}